import { NextResponse } from 'next/server';

// Extension data interface
export interface GalleryExtension {
  id: string;
  name: string;
  description: string;
  installCommand: string;
  category?: string;
  icon?: string;
}

// Pre-defined extension list from geminicli.com/extensions/
const extensionsData: GalleryExtension[] = [
  // Spotlight Extensions
  {
    id: 'adb-control-gemini',
    name: 'ADB Control',
    description: 'Control Android devices via ADB with Gemini CLI using /android commands',
    installCommand: 'gemini extensions install https://github.com/tiendung2k03/adb-control-gemini',
    category: 'Spotlight',
  },
  {
    id: 'palladius-common-commands',
    name: 'Palladius Common Commands',
    description: 'Ricc\'s golden custom commands',
    installCommand: 'gemini extensions install https://github.com/palladius/gemini-cli-custom-commands',
    category: 'Spotlight',
  },
  {
    id: 'gcloud',
    name: 'Google Cloud',
    description: 'Enable MCP-compatible AI agents to interact with Google Cloud',
    installCommand: 'gemini extensions install https://github.com/gemini-cli-extensions/gcloud',
    category: 'Spotlight',
  },
  // All Extensions
  {
    id: 'context7',
    name: 'Context7',
    description: 'Up-to-date code docs for any prompt',
    installCommand: 'gemini extensions install https://github.com/upstash/context7',
    category: 'Documentation',
  },
  {
    id: 'github',
    name: 'GitHub',
    description: 'GitHub\'s official MCP Server',
    installCommand: 'gemini extensions install https://github.com/github/github-mcp-server',
    category: 'Development',
  },
  {
    id: 'mcp-toolbox-for-databases',
    name: 'MCP Toolbox for Databases',
    description: '30+ datasources for database operations',
    installCommand: 'gemini extensions install https://github.com/googleapis/genai-toolbox',
    category: 'Database',
  },
  {
    id: 'clasp',
    name: 'CLASP',
    description: 'Manage Google Apps Script projects',
    installCommand: 'gemini extensions install https://github.com/google/clasp',
    category: 'Google',
  },
  {
    id: 'exa-mcp-server',
    name: 'Exa MCP Server',
    description: 'Web search, crawling, and technical code docs',
    installCommand: 'gemini extensions install https://github.com/exa-labs/exa-mcp-server',
    category: 'Search',
  },
  {
    id: 'mcp-server-browserbase',
    name: 'Browserbase',
    description: 'Control browsers with Browserbase and Stagehand',
    installCommand: 'gemini extensions install https://github.com/browserbase/mcp-server-browserbase',
    category: 'Browser',
  },
  {
    id: 'conductor',
    name: 'Conductor',
    description: 'Specify, plan, and implement software features',
    installCommand: 'gemini extensions install https://github.com/gemini-cli-extensions/conductor',
    category: 'Development',
  },
  {
    id: 'grafana',
    name: 'Grafana',
    description: 'MCP server for Grafana',
    installCommand: 'gemini extensions install https://github.com/grafana/mcp-grafana',
    category: 'DevOps',
  },
  {
    id: 'mcp-server-kubernetes',
    name: 'Kubernetes',
    description: 'Kubernetes management commands',
    installCommand: 'gemini extensions install https://github.com/Flux159/mcp-server-kubernetes',
    category: 'DevOps',
  },
  {
    id: 'stripe',
    name: 'Stripe',
    description: 'Build AI-powered products with Stripe',
    installCommand: 'gemini extensions install https://github.com/stripe/ai',
    category: 'Finance',
  },
  {
    id: 'huggingface-skills',
    name: 'Hugging Face Skills',
    description: 'Access Hugging Face Skills',
    installCommand: 'gemini extensions install https://github.com/huggingface/skills',
    category: 'AI/ML',
  },
  {
    id: 'terraform',
    name: 'Terraform',
    description: 'Terraform MCP Server for IaC automation',
    installCommand: 'gemini extensions install https://github.com/hashicorp/terraform-mcp-server',
    category: 'DevOps',
  },
  {
    id: 'elevenlabs',
    name: 'ElevenLabs',
    description: 'Text-to-speech, voice design, audio processing',
    installCommand: 'gemini extensions install https://github.com/elevenlabs/elevenlabs-mcp',
    category: 'Audio',
  },
  {
    id: 'cloudbase-ai-toolkit',
    name: 'Tencent CloudBase',
    description: 'Tencent CloudBase AI development toolkit',
    installCommand: 'gemini extensions install https://github.com/TencentCloudBase/CloudBase-MCP',
    category: 'Cloud',
  },
  {
    id: 'mcp-neo4j',
    name: 'Neo4j',
    description: 'Neo4j Labs Model Context Protocol servers',
    installCommand: 'gemini extensions install https://github.com/neo4j-contrib/mcp-neo4j',
    category: 'Database',
  },
  {
    id: 'nanobanana',
    name: 'Nanobanana',
    description: 'Generate and manipulate images with text prompts',
    installCommand: 'gemini extensions install https://github.com/gemini-cli-extensions/nanobanana',
    category: 'Media',
  },
  {
    id: 'gemini-cli-security',
    name: 'Security',
    description: 'Find vulnerabilities in code changes and PRs',
    installCommand: 'gemini extensions install https://github.com/gemini-cli-extensions/security',
    category: 'Security',
  },
  {
    id: 'cloud-run',
    name: 'Cloud Run',
    description: 'Deploy apps to Cloud Run',
    installCommand: 'gemini extensions install https://github.com/GoogleCloudPlatform/cloud-run-mcp',
    category: 'Google',
  },
  {
    id: 'open-aware',
    name: 'Open Aware',
    description: 'Deep Code Research Agent for complex codebases',
    installCommand: 'gemini extensions install https://github.com/qodo-ai/open-aware',
    category: 'Development',
  },
  {
    id: 'redis',
    name: 'Redis',
    description: 'Manage and search data in Redis',
    installCommand: 'gemini extensions install https://github.com/redis/mcp-redis',
    category: 'Database',
  },
  {
    id: 'sonarqube-mcp-server',
    name: 'SonarQube',
    description: 'Code quality and security integration',
    installCommand: 'gemini extensions install https://github.com/SonarSource/sonarqube-mcp-server',
    category: 'Security',
  },
  {
    id: 'pickle-rick',
    name: 'Pickle Rick',
    description: '"Pickle Rick" engineering persona extension',
    installCommand: 'gemini extensions install https://github.com/galz10/pickle-rick-extension',
    category: 'Fun',
  },
  {
    id: 'monday',
    name: 'Monday.com',
    description: 'Manage monday.com projects and tasks',
    installCommand: 'gemini extensions install https://github.com/mondaycom/mcp',
    category: 'Productivity',
  },
  {
    id: 'code-review',
    name: 'Code Review',
    description: 'Google\'s Code Review extension',
    installCommand: 'gemini extensions install https://github.com/gemini-cli-extensions/code-review',
    category: 'Development',
  },
  {
    id: 'flutter',
    name: 'Flutter',
    description: 'Flutter and Dart-related commands',
    installCommand: 'gemini extensions install https://github.com/gemini-cli-extensions/flutter',
    category: 'Development',
  },
  {
    id: 'google-workspace',
    name: 'Google Workspace',
    description: 'Access Google Workspace',
    installCommand: 'gemini extensions install https://github.com/gemini-cli-extensions/workspace',
    category: 'Google',
  },
  {
    id: 'atlassian-rovo-mcp-server',
    name: 'Atlassian Rovo',
    description: 'Connect Jira and Confluence with AI',
    installCommand: 'gemini extensions install https://github.com/atlassian/atlassian-mcp-server',
    category: 'Productivity',
  },
  {
    id: 'gemini-cli-jules',
    name: 'Jules',
    description: 'Orchestrate Jules async agent',
    installCommand: 'gemini extensions install https://github.com/gemini-cli-extensions/jules',
    category: 'Development',
  },
  {
    id: 'gemini-cli-prompt-library',
    name: 'Prompt Library',
    description: 'Curated prompts for development tasks',
    installCommand: 'gemini extensions install https://github.com/harish-garg/gemini-cli-prompt-library',
    category: 'Development',
  },
  {
    id: 'stitch',
    name: 'Stitch',
    description: 'Generate UI from Text, Image',
    installCommand: 'gemini extensions install https://github.com/gemini-cli-extensions/stitch',
    category: 'UI/UX',
  },
  {
    id: 'gemini-kit',
    name: 'Gemini Kit',
    description: 'Team of AI Agents for software development',
    installCommand: 'gemini extensions install https://github.com/nth5693/gemini-kit',
    category: 'AI/ML',
  },
  {
    id: 'mcp-server-milvus',
    name: 'Milvus',
    description: 'Model Context Protocol for Milvus',
    installCommand: 'gemini extensions install https://github.com/zilliztech/mcp-server-milvus',
    category: 'Database',
  },
  {
    id: 'apify-agent-skills',
    name: 'Apify Agent Skills',
    description: 'Web scraping and automation skills',
    installCommand: 'gemini extensions install https://github.com/apify/agent-skills',
    category: 'Automation',
  },
  {
    id: 'dynatrace-mcp-server',
    name: 'Dynatrace',
    description: 'Dynatrace Observability MCP server',
    installCommand: 'gemini extensions install https://github.com/dynatrace-oss/dynatrace-mcp',
    category: 'DevOps',
  },
  {
    id: 'huggingface',
    name: 'Hugging Face',
    description: 'Access the Hugging Face Hub',
    installCommand: 'gemini extensions install https://github.com/huggingface/hf-mcp-server',
    category: 'AI/ML',
  },
  {
    id: 'ralph',
    name: 'Ralph',
    description: 'Ralph loops extension',
    installCommand: 'gemini extensions install https://github.com/gemini-cli-extensions/ralph',
    category: 'Development',
  },
  {
    id: 'postman-api-mcp',
    name: 'Postman API',
    description: 'Connect AI to Postman APIs',
    installCommand: 'gemini extensions install https://github.com/postmanlabs/postman-mcp-server',
    category: 'API',
  },
  {
    id: 'genkit',
    name: 'Genkit',
    description: 'Build full-stack AI apps',
    installCommand: 'gemini extensions install https://github.com/gemini-cli-extensions/genkit',
    category: 'AI/ML',
  },
  {
    id: 'uuv',
    name: 'UUV',
    description: 'BDD assistance based on accessibility',
    installCommand: 'gemini extensions install https://github.com/e2e-test-quest/uuv',
    category: 'Testing',
  },
  {
    id: 'mcp-confluent',
    name: 'Confluent',
    description: 'Confluent MCP server',
    installCommand: 'gemini extensions install https://github.com/confluentinc/mcp-confluent',
    category: 'Data',
  },
  {
    id: 'gke-mcp',
    name: 'GKE',
    description: 'Google Kubernetes Engine extension',
    installCommand: 'gemini extensions install https://github.com/GoogleCloudPlatform/gke-mcp',
    category: 'Google',
  },
  {
    id: 'skill-porter',
    name: 'Skill Porter',
    description: 'Convert Claude Code skills to Gemini',
    installCommand: 'gemini extensions install https://github.com/jduncan-rva/skill-porter',
    category: 'Development',
  },
  {
    id: 'firebase',
    name: 'Firebase',
    description: 'Firebase backend and AI infrastructure',
    installCommand: 'gemini extensions install https://github.com/gemini-cli-extensions/firebase',
    category: 'Google',
  },
  {
    id: 'falcon-mcp',
    name: 'CrowdStrike Falcon',
    description: 'CrowdStrike Falcon security analysis',
    installCommand: 'gemini extensions install https://github.com/CrowdStrike/falcon-mcp',
    category: 'Security',
  },
  {
    id: 'gemini-cli-ralph',
    name: 'Ralph Wiggum',
    description: 'Ralph Wiggum extension',
    installCommand: 'gemini extensions install https://github.com/AsyncFuncAI/ralph-wiggum-extension',
    category: 'Fun',
  },
  {
    id: 'ack-mcp-server',
    name: 'Alibaba Cloud ACK',
    description: 'Alibaba Cloud container operations',
    installCommand: 'gemini extensions install https://github.com/aliyun/alibabacloud-ack-mcp-server',
    category: 'Cloud',
  },
  {
    id: 'figma',
    name: 'Figma',
    description: 'Generate code from Figma frames',
    installCommand: 'gemini extensions install https://github.com/figma/figma-gemini-cli-extension',
    category: 'UI/UX',
  },
  {
    id: 'criticalthink',
    name: 'Critical Think',
    description: 'Skepticism countermeasure for AI responses',
    installCommand: 'gemini extensions install https://github.com/abagames/slash-criticalthink',
    category: 'Development',
  },
  {
    id: 'elasticsearch',
    name: 'Elasticsearch',
    description: 'Official Elasticsearch extension',
    installCommand: 'gemini extensions install https://github.com/elastic/gemini-cli-elasticsearch',
    category: 'Database',
  },
  {
    id: 'auth0',
    name: 'Auth0',
    description: 'Manage Auth0 tenants, apps, APIs',
    installCommand: 'gemini extensions install https://github.com/auth0/auth0-mcp-server',
    category: 'Security',
  },
  {
    id: 'google-maps-platform',
    name: 'Google Maps',
    description: 'Google Maps Platform documentation',
    installCommand: 'gemini extensions install https://github.com/googlemaps/platform-ai',
    category: 'Google',
  },
  {
    id: 'hcom',
    name: 'HCOM',
    description: 'Connect Claude Code, Gemini CLI, Codex',
    installCommand: 'gemini extensions install https://github.com/aannoo/hcom',
    category: 'Integration',
  },
  {
    id: 'google-workspace-developer-tools',
    name: 'Google Workspace Dev Tools',
    description: 'Google Workspace Developer Tools',
    installCommand: 'gemini extensions install https://github.com/googleworkspace/developer-tools',
    category: 'Google',
  },
  {
    id: 'mcp-toolbox',
    name: 'MCP Toolbox',
    description: 'Load custom tools using MCP Toolbox',
    installCommand: 'gemini extensions install https://github.com/gemini-cli-extensions/mcp-toolbox',
    category: 'Development',
  },
  {
    id: 'skillz',
    name: 'Skillz',
    description: 'Load Claude-style skills into Gemini',
    installCommand: 'gemini extensions install https://github.com/intellectronica/gemini-cli-skillz',
    category: 'Development',
  },
  {
    id: 'computer-use',
    name: 'Computer Use',
    description: 'Autonomous web browsing and testing',
    installCommand: 'gemini extensions install https://github.com/automateyournetwork/GeminiCLI_ComputerUse_Extension',
    category: 'Automation',
  },
  {
    id: 'endor-labs-code-security',
    name: 'Endor Labs',
    description: 'Secure copilot for coding assistants',
    installCommand: 'gemini extensions install https://github.com/endorlabs/gemini-extension',
    category: 'Security',
  },
  {
    id: 'postgres',
    name: 'PostgreSQL',
    description: 'Connect PostgreSQL database',
    installCommand: 'gemini extensions install https://github.com/gemini-cli-extensions/postgres',
    category: 'Database',
  },
  {
    id: 'web-accessibility',
    name: 'Web Accessibility',
    description: 'Find and fix web accessibility violations',
    installCommand: 'gemini extensions install https://github.com/gemini-cli-extensions/web-accessibility',
    category: 'Accessibility',
  },
  {
    id: 'blueprint',
    name: 'Blueprint',
    description: 'Guide software development',
    installCommand: 'gemini extensions install https://github.com/gplasky/gemini-cli-blueprint-extension',
    category: 'Development',
  },
  {
    id: 'spec-flow',
    name: 'Spec Flow',
    description: 'Spec-Driven Development toolkit',
    installCommand: 'gemini extensions install https://github.com/marcusgoll/Spec-Flow',
    category: 'Development',
  },
  {
    id: 'miro',
    name: 'Miro',
    description: 'AI access to Miro boards',
    installCommand: 'gemini extensions install https://github.com/miroapp/miro-ai',
    category: 'Productivity',
  },
  {
    id: 'godoctor',
    name: 'Go Doctor',
    description: 'AI-powered Go development assistant',
    installCommand: 'gemini extensions install https://github.com/danicat/godoctor',
    category: 'Development',
  },
  {
    id: 'gemini-ralph-loop',
    name: 'Gemini Ralph Loop',
    description: 'Self-referential iterative loops',
    installCommand: 'gemini extensions install https://github.com/kranthik123/Gemini-Ralph-Loop',
    category: 'Development',
  },
  {
    id: 'pinecone-mcp',
    name: 'Pinecone',
    description: 'Connect Pinecone projects',
    installCommand: 'gemini extensions install https://github.com/pinecone-io/pinecone-mcp',
    category: 'Database',
  },
  {
    id: 'firebase-rules',
    name: 'Firebase Rules',
    description: 'Security rules snippets',
    installCommand: 'gemini extensions install https://github.com/firebase/snippets-rules',
    category: 'Security',
  },
  {
    id: 'gemini-cloud-assist',
    name: 'Gemini Cloud Assist',
    description: 'GCP tasks assistance',
    installCommand: 'gemini extensions install https://github.com/GoogleCloudPlatform/gemini-cloud-assist-mcp',
    category: 'Google',
  },
  {
    id: 'gemini-docs-ext',
    name: 'Gemini Docs',
    description: 'Gemini API docs and MCP',
    installCommand: 'gemini extensions install https://github.com/markmcd/gemini-docs-ext',
    category: 'Documentation',
  },
  {
    id: 'mcp-tts',
    name: 'MCP TTS',
    description: 'Text-to-Speech announcements',
    installCommand: 'gemini extensions install https://github.com/blacktop/mcp-tts',
    category: 'Audio',
  },
  {
    id: 'vision',
    name: 'Vision',
    description: 'Webcam/iPhone camera capture',
    installCommand: 'gemini extensions install https://github.com/automateyournetwork/GeminiCLI_Vision_Extension',
    category: 'Media',
  },
  {
    id: 'globalping',
    name: 'Globalping',
    description: 'Network measurements and benchmarks',
    installCommand: 'gemini extensions install https://github.com/jsdelivr/globalping-mcp-server',
    category: 'Network',
  },
  {
    id: 'ipsw-skill',
    name: 'IPSW',
    description: 'Apple firmware reverse engineering',
    installCommand: 'gemini extensions install https://github.com/blacktop/ipsw-skill',
    category: 'Security',
  },
  {
    id: 'google-adk-agent-extension',
    name: 'Google ADK Agent',
    description: 'Google ADK AI Agent Application',
    installCommand: 'gemini extensions install https://github.com/simonliu-ai-product/adk-agent-extension',
    category: 'Google',
  },
  {
    id: 'google-ads-api-developer-assistant',
    name: 'Google Ads API',
    description: 'Google Ads API assistant',
    installCommand: 'gemini extensions install https://github.com/googleads/google-ads-api-developer-assistant',
    category: 'Google',
  },
  {
    id: 'gemini-deep-research',
    name: 'Deep Research',
    description: 'Deep research extension',
    installCommand: 'gemini extensions install https://github.com/allenhutchison/gemini-cli-deep-research',
    category: 'Research',
  },
  {
    id: 'outline-driven-development',
    name: 'Outline Driven Dev',
    description: 'AST analysis with context engineering',
    installCommand: 'gemini extensions install https://github.com/OutlineDriven/outline-driven-development',
    category: 'Development',
  },
  {
    id: 'speedgrapher',
    name: 'Speedgrapher',
    description: 'MCP server for writers',
    installCommand: 'gemini extensions install https://github.com/danicat/speedgrapher',
    category: 'Writing',
  },
  {
    id: 'antigravity-swarm',
    name: 'Antigravity Swarm',
    description: 'Deploy autonomous sub-agents',
    installCommand: 'gemini extensions install https://github.com/wjgoarxiv/antigravity-swarm',
    category: 'Development',
  },
  {
    id: 'bigquery-data-analytics',
    name: 'BigQuery Analytics',
    description: 'BigQuery data insights',
    installCommand: 'gemini extensions install https://github.com/gemini-cli-extensions/bigquery-data-analytics',
    category: 'Google',
  },
  {
    id: 'bitrise',
    name: 'Bitrise',
    description: 'Bitrise API MCP server',
    installCommand: 'gemini extensions install https://github.com/bitrise-io/bitrise-mcp',
    category: 'DevOps',
  },
  {
    id: 'vault',
    name: 'HashiCorp Vault',
    description: 'HashiCorp Vault MCP',
    installCommand: 'gemini extensions install https://github.com/hashicorp/vault-mcp-server',
    category: 'Security',
  },
  {
    id: 'gemini-plan-commands',
    name: 'Plan Commands',
    description: 'Create, implement, deploy plans',
    installCommand: 'gemini extensions install https://github.com/ddobrin/gemini-plan-commands',
    category: 'Development',
  },
  {
    id: 'file-search',
    name: 'File Search',
    description: 'Cloud RAG via Gemini File Search',
    installCommand: 'gemini extensions install https://github.com/automateyournetwork/GeminiCLI_File_Search_Extension',
    category: 'Search',
  },
  {
    id: 'looker',
    name: 'Looker',
    description: 'Connect to Looker',
    installCommand: 'gemini extensions install https://github.com/gemini-cli-extensions/looker',
    category: 'Data',
  },
  {
    id: 'swiftwasm-skills',
    name: 'SwiftWasm',
    description: 'SwiftWasm Skills',
    installCommand: 'gemini extensions install https://github.com/swiftwasm/skills',
    category: 'Development',
  },
  {
    id: 'youtube-to-docs',
    name: 'YouTube to Docs',
    description: 'Convert YouTube videos to docs',
    installCommand: 'gemini extensions install https://github.com/DoIT-Artificial-Intelligence/youtube-to-docs',
    category: 'Documentation',
  },
];

// Get unique categories
const categories = [...new Set(extensionsData.map(ext => ext.category).filter(Boolean))];

export async function GET() {
  try {
    return NextResponse.json({
      extensions: extensionsData,
      categories: categories,
      total: extensionsData.length,
    });
  } catch (error) {
    console.error('Error fetching extensions gallery:', error);
    return NextResponse.json(
      { error: 'Failed to fetch extensions gallery' },
      { status: 500 }
    );
  }
}
